const DAY=86400000;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export const addDays=(iso,n)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const daysBetween=(a,b)=>Math.round((new Date(`${b}T12:00:00Z`)-new Date(`${a}T12:00:00Z`))/DAY);

export const KIRK_HADIS_META={
  id:'nevevi-kirk-hadis-baslangic',
  title:'Kırk Hadis',
  author:'İmam Nevevî',
  routeTitle:'Başlangıç İlim Rotası',
  level:'Başlangıç',
  activeUnits:42,
  totalUnits:42,
  rightsMode:'public-domain-source-original-translation',
  rightsNote:'Arapça hadis metni açık kaynak veri setinden alınır. Türkçe tam tercümeler Manevî Rota için Arapça metinden özgün olarak hazırlanmıştır; modern bir yayınevi tercümesi kopyalanmaz.',
  editorialNote:'Her hadiste Arapça metin, Manevî Rota tarafından hazırlanmış Türkçe tam tercüme ve ayrıca kısa editoryal açıklama birlikte gösterilir.'
};

const u=(id,title,source,meaning,why,reflection,practice,sections)=>({id,title,source,meaning,why,reflection,practice,sections});
export const KIRK_HADIS_UNITS=[
  u(1,'Niyet','Nevevî 1 · Buhârî ve Müslim','Amelin yönünü ve değerini belirleyen temel unsurlardan biri niyettir; kişi yönelişine göre karşılık görür.','İlim yoluna başlarken “ne kadar okuyacağım?”dan önce “niçin okuyorum?” sorusunu berraklaştırır.','Bugün okumaya başlarken tek cümlelik niyetin ne?','Bir işe başlamadan önce 10 saniye dur ve niyetini zihninde netleştir.',[
    'Başlangıçta büyük hedefler heyecan verir; fakat niyet net değilse hedef kolayca gösteriye, sayıya veya kıyaslamaya dönüşebilir. Bu rota bu yüzden ilk gün miktarı değil yönü konuşur.',
    'Niyet bir kez yazılıp unutulan slogan değildir. Aynı çalışma zaman içinde farklı saiklerle yapılabilir. Kişinin kendine ara sıra “Bunu neden yapıyorum?” diye sorması, rotasını düzeltmesine yardım eder.',
    'İlim öğrenme niyeti; bilmek, doğru yaşamak, fayda üretmek ve hatayı azaltmak gibi somut karşılıklar taşıyabilir. Uygulama niyeti puanlamaz; yalnızca senin kendi cümleni saklar.'
  ]),
  u(2,'İslam, iman ve ihsan','Nevevî 2 · Müslim (Cibril hadisi)','Meşhur Cibril hadisinde İslam, iman ve ihsan kavramları ile kıyamete dair sorular bir öğretim düzeni içinde ele alınır.','Dinî bilgiyi tek bir başlığa sıkıştırmadan; amel, inanç ve kulluk bilincinin birlikte düşünülmesini sağlar.','Bilgi, davranış ve iç disiplin arasında sende en çok hangi alan güçlenmeye ihtiyaç duyuyor?','Bugün öğrendiğin bir bilgiyi davranışa çevirecek tek küçük adım seç.',[
    'Bu hadis, öğretimin soru-cevap yoluyla nasıl katmanlı ilerleyebileceğine güçlü bir örnektir. İlk seviye rotada amaç kavramların bütün ayrıntısını tüketmek değil, aralarındaki ilişkiyi fark etmektir.',
    'İslam başlığında görünür ameller; iman başlığında inanılması gereken esaslar; ihsan başlığında ise kulluğun bilinç ve murakabe boyutu öne çıkar. Bunlar birbirine rakip alanlar değil, aynı yolculuğun farklı yüzleridir.',
    'Manevî Rota da bu yüzden yalnızca “görev yaptın mı?” sorusuna sıkışmaz. Okuma, ibadet ve davranış taraflarını ayrı ayrı izler; fakat bir maneviyat skoru üretmez.'
  ]),
  u(3,'İslam’ın beş temel esası','Nevevî 3 · Buhârî ve Müslim','İslam’ın temel yapısı şehadet, namaz, zekât, oruç ve hac gibi ana esaslarla anlatılır.','Öncelik sırasını hatırlatır: ayrıntılara açılmadan önce temellerin yerini bilmek gerekir.','Hayatında “temel” olanla “ek” olanı ayırmakta zorlandığın bir alan var mı?','Bugün bir temel sorumluluğu daha sakin ve dikkatli yapmaya odaklan.',[
    'İlim yolunda kaynak çokluğu bazen öncelik duygusunu zayıflatır. İnsan aynı anda onlarca konuya açılınca temel meseleler arka planda kalabilir. Bu hadis, yapının taşıyıcı unsurlarını hatırlatan bir çerçeve sunar.',
    'Başlangıç müfredatında da benzer ilke kullanılır: önce temel kavramlar ve farz bilgisi, sonra ayrıntılı tartışmalar. Zor kitabı erken okumak ilerilik göstergesi değildir; doğru sırada okumak daha değerlidir.',
    'Uygulama bu nedenle yeni kitap açmayı “seviye atlama ödülü” gibi değil, önceki temel yeterince oturduğunda kontrollü bir sonraki adım olarak ele alır.'
  ]),
  u(4,'Yaratılış, ömür ve kader','Nevevî 4 · Buhârî ve Müslim','İnsanın anne rahmindeki yaratılış safhaları ve hayatına dair takdir edilen hususlar üzerinden kader ve son hâl üzerine düşünmeye çağıran bir rivayettir.','Başlangıç düzeyinde kader konusuna girerken tek cümlelik sloganlar yerine ölçülü ve kaynaklı düşünme ihtiyacını gösterir.','Kader konuşurken bilgi ile tahmin arasındaki sınırı nasıl koruyabilirsin?','Anlamadığın bir itikadî soruyu kesin hükme çevirmek yerine “araştırılacaklar” listene ekle.',[
    'Kader başlığı, kısa özetlerin kolayca yanlış anlaşılabildiği alanlardan biridir. Bu nedenle rota burada ayrıntılı hüküm öğretmek yerine, soruyu doğru kaynağa taşıma alışkanlığı kazandırmayı hedefler.',
    'Rivayetin ana çerçevesi insanın yaratılışı, ömrü ve akıbeti üzerinde düşünmeye açılır. Ancak kader konusu; sorumluluk, irade ve ilahî ilim gibi başka kavramlarla birlikte çalışılmalıdır.',
    'Bu ünitede “tek başıma sonuç çıkarayım” yaklaşımı yerine güvenilir akaid kaynaklarına geçiş için bir işaret bırakıyoruz. İleri rota, bu soruları ayrı bir akaid müfredatına taşıyacak.'
  ]),
  u(5,'Dinde sonradan ortaya konan şeyler','Nevevî 5 · Buhârî ve Müslim','Dinin kendi ölçülerine dayanmayan bir şeyi dine aitmış gibi ortaya koymanın reddedileceğini bildiren temel rivayetlerden biridir.','Kaynak ve delil disiplininin neden gerekli olduğunu çok erken aşamada öğretir.','Bir dinî bilgi duyduğunda “kaynağı nedir?” sorusunu ne sıklıkla soruyorsun?','Bugün karşılaştığın bir dinî iddianın kaynağını kontrol et.',[
    'Dinî içerik üretiminde güzel görünmek veya çok paylaşılmak doğruluk ölçüsü değildir. Bu yüzden Manevî Rota’nın içerik kütüphanesinde her metin için kaynak, hak durumu ve editoryal not tutmayı hedefliyoruz.',
    'Bu hadis, her yeniliği gündelik anlamda kötüleme cümlesi olarak kullanılmamalıdır. Fıkıh ve usul literatüründe konunun kavramları, kapsamı ve uygulaması daha ayrıntılı ele alınır.',
    'Başlangıç seviyesinde çıkarılacak pratik ders şudur: din adına kesin bir cümle kurmadan önce onun dayanağını öğren. Kaynak kontrolü, ilim yolunun temel adabıdır.'
  ]),
  u(6,'Helal, haram ve şüpheli alan','Nevevî 6 · Buhârî ve Müslim','Helal ve haramın açık olduğu, arada insanların bir kısmının hükmünü bilmediği şüpheli meselelerin bulunabileceği anlatılır; kalbin ıslahına da dikkat çekilir.','Bilginin sadece “evet/hayır” cevaplarından ibaret olmadığını; bazen ihtiyat, araştırma ve ehline sorma gerektiğini öğretir.','Bilmediğin konuda hemen karar vermek mi, durup araştırmak mı sana daha zor geliyor?','Bugün emin olmadığın bir dinî konuda kesin konuşmak yerine not al ve güvenilir kaynağa sor.',[
    'Başlangıç öğrencisinin önemli becerilerinden biri “bilmiyorum” diyebilmektir. Her meseleyi anında sınıflandırma ihtiyacı, yanlış güven üretebilir.',
    'Şüpheli alan fikri, özellikle günlük hayatta ihtiyat ve kaynak danışma davranışını öğretir. Burada amaç vesvese üretmek değil; hükmü bilinmeyen konuyu doğru yöntemle araştırmaktır.',
    'Rivayette kalbe yapılan vurgu da önemlidir. Dış davranışın yanında niyet, hassasiyet ve iç yönelişin ihmal edilmemesi gerektiğini hatırlatır.'
  ]),
  u(7,'Din samimi nasihattir','Nevevî 7 · Müslim','Dinî hayatın merkezinde samimiyet, iyilik isteme ve doğru öğüt anlayışının bulunduğunu anlatan kısa fakat kapsamlı bir rivayettir.','İlim öğrenmenin yalnız kişisel birikim değil, doğru üslup ve fayda sorumluluğu taşıdığını hatırlatır.','Birine doğru bir şeyi söylerken üslubun o sözün faydasını nasıl etkiliyor?','Bugün bir kişiye fayda sağlayacak küçük, nazik ve gösterişsiz bir iyilik yap.',[
    'Nasihat kelimesi yalnız “birine öğüt vermek” anlamına indirgenmemelidir. Klasik açıklamalarda samimiyet, hayır isteme ve bağlılık gibi daha geniş anlam katmanlarıyla ele alınır.',
    'İlim arttıkça üslubun sertleşmesi zorunlu değildir. Aksine bilgi, muhatabın hâlini gözetme ve faydayı önceleme sorumluluğunu büyütebilir.',
    'İlk 7 günlük rotayı bu hadisle kapatmamızın sebebi budur: okuma yalnız zihinde birikmesin; davranışa, nezakete ve faydaya açılan bir yönü olsun.'
  ]),
  u(8,"Can ve mal dokunulmazlığı","Nevevî 8 · Buhârî ve Müslim","İman ikrarı ve temel dinî sorumluluklarla birlikte can ve mal dokunulmazlığını konu eden; klasik fıkıhta kamu düzeni ve hukuk bağlamında ele alınan bir rivayettir.","Bu hadis, dinî metinleri tarihî ve fıkhî bağlamından koparmadan okumayı öğretmek için önemlidir.","Bir hadisi okurken metin, bağlam ve fıkhî uygulama alanını birbirinden ayırabiliyor musun?","Bugün hüküm içeren bir rivayette “bunun uygulama bağlamı nedir?” sorusunu not et.",["Bu tür rivayetler bireysel şiddet çağrısı olarak okunamaz. Klasik hukukta can ve mal dokunulmazlığı, kamu otoritesi ve yargı düzeni içinde ele alınır.","Başlangıç öğrencisi için ana beceri, tek bir cümleden bağımsız hukuk hükmü üretmemek; şerh ve fıkıh kaynaklarına başvurmaktır."]),
  u(9,"Yasaklardan kaçınmak, emirde gücü gözetmek","Nevevî 9 · Buhârî ve Müslim","Yasaklardan sakınmayı; emredilenleri ise kişinin gücü yettiği ölçüde yerine getirmesini vurgulayan bir rivayettir.","Manevî programda “her şeyi bir anda yapma” baskısı yerine kapasiteye göre sürdürülebilir ilerlemenin dayanağını hatırlatır.","Bugün kendine gereksiz yere ağırlaştırdığın bir hedef var mı?","Bir hedefi gerçek kapasitenle uyumlu en küçük sürdürülebilir hâline indir.",["Dinî sorumlulukları anlamada güç yetirebilme ilkesi önemlidir; ancak bu, kişisel keyfe göre hüküm kaldırmak anlamına gelmez.","Aşırı soru üretmek ile gerekli ilmi soru sormak aynı şey değildir. Amaç, gereksiz karmaşadan kaçınırken doğru bilgiyi ehline sormaktır."]),
  u(10,"Helal kazanç ve duanın temiz zemini","Nevevî 10 · Müslim","Allah’ın temiz olanı kabul etmesi, helal rızık ve kişinin hayatındaki kazanç-tüketim tercihlerinin dua ve kullukla ilişkisi üzerinde durur.","İbadeti hayatın ekonomik ve etik tercihlerinden koparmamayı öğretir.","Kazanç ve tüketim tercihlerinde “helal ve temiz” hassasiyetini nerede güçlendirebilirsin?","Bugün harcama veya kazançlarından birini bilinçli biçimde gözden geçir.",["Rivayet, dua eden kişinin dış görünüşünden çok hayatının helal-haram duyarlılığına dikkat çeker.","Başlangıç rotasında amaç ayrıntılı fetva üretmek değil; şüpheli alanlarda güvenilir fıkıh kaynağına yönelme alışkanlığıdır."]),
  u(11,"Şüpheyi bırak, güven verene yönel","Nevevî 11 · Tirmizî ve Nesâî","İçinde güçlü şüphe uyandıran şeyi bırakıp daha güvenli ve açık olana yönelmeyi tavsiye eden kısa bir ölçüdür.","Karar verirken sürekli kararsızlık ile sağlıklı ihtiyat arasındaki farkı düşünmeye yardım eder.","Bugün seni gereksiz yere zihnen yoran bir şüphe var mı; bilgiyle mi yoksa vesveseyle mi besleniyor?","Şüpheli bir meselede kaynak kontrolü yap; çözülmüyorsa ehline sor.",["Bu ilke vesveseyi büyütmek için değil, kalıcı şüphe durumunda güvenilir bilgiye yönelmek için okunmalıdır.","Fıkhî hüküm gerektiren meselelerde yalnız iç huzur ölçüsü yeterli değildir; kaynak ve ehil görüş gerekir."]),
  u(12,"Seni ilgilendirmeyeni bırakmak","Nevevî 12 · Tirmizî ve İbn Mâce","Kişinin dinî ve ahlâkî olgunluğunun, kendisini ilgilendirmeyen gereksiz iş ve sözlerden uzak durmasıyla ilişkisini anlatır.","Dikkatin dağılmasını azaltır ve ilim yolunda “her tartışmaya yetişme” dürtüsünü sınırlar.","Vaktini en çok tüketip sana gerçek fayda vermeyen konu ne?","Bugün bir gereksiz tartışmayı veya dikkat dağıtıcı alışkanlığı bilinçli olarak bırak.",["“Beni ilgilendirmiyor” ifadesi toplumsal sorumluluktan kaçmak için kullanılmamalıdır.","Asıl ders, faydasız merak ve gereksiz müdahaleyi azaltıp sorumluluk alanına odaklanmaktır."]),
  u(13,"Kendin için istediğini kardeşin için istemek","Nevevî 13 · Buhârî ve Müslim","İman ahlâkının, kişinin kendisi için sevdiği hayrı başkaları için de istemesiyle olgunlaştığını anlatır.","İlim ve maneviyatın bencilliğe değil, başkası için hayır istemeye açılması gerektiğini hatırlatır.","Bir başkasının başarısını kendi başarın kadar içtenlikle isteyebildiğin bir alan var mı?","Bugün birinin faydasına olacak küçük bir destek ver.",["Haset ve kıyas, öğrenme yolculuğunda kolayca motivasyonu bozar.","Bu hadis, rekabet yerine ortak hayrı ve kardeşlik duygusunu güçlendiren bir ölçü sunar."]),
  u(14,"Hayatın dokunulmazlığı ve hukuk sınırı","Nevevî 14 · Buhârî ve Müslim","Klasik İslam hukukunda can dokunulmazlığının istisnalarının yargı ve hukuk bağlamında ele alındığı bir rivayettir.","Ceza hukukuyla ilgili metinlerin bireysel uygulama değil, yetkili hukuk düzeni ve usul bağlamında okunması gerektiğini öğretir.","Hukuk içeren bir hadisle karşılaşınca hangi ek kaynaklara ihtiyaç duyduğunu fark ediyor musun?","Bu hadisi “araştır” etiketiyle kaydet ve bir fıkıh/usul kaynağıyla birlikte çalış.",["Bu rivayet bireysel cezalandırma yetkisi vermez; klasik literatürde şartlar, ispat ve kamu otoritesi çerçevesinde ele alınır.","Başlangıç seviyesinde hedef hükmü tek başına uygulamaya çevirmek değil, hukuk metnini bağlamıyla okumayı öğrenmektir."]),
  u(15,"İyi konuşmak, komşu ve misafire ikram","Nevevî 15 · Buhârî ve Müslim","İmanla güzel söz veya susma, komşuya iyilik ve misafire ikram arasında bağ kuran kapsamlı bir ahlâk rivayetidir.","Maneviyatı sadece özel ibadetlerden ibaret görmeyip günlük ilişkilerde görünür hâle getirir.","Bugün dilini, komşuluğunu veya misafirperverliğini hangi küçük davranışla güzelleştirebilirsin?","Konuşmadan önce “bu söz hayır üretiyor mu?” diye bir kez dur.",["Susmak her durumda doğru değildir; hak ve sorumluluk gerektiren yerde güzel ve ölçülü söz önemlidir.","Hadis, iman iddiasının sosyal nezaket ve sorumlulukta karşılık bulmasını ister."]),
  u(16,"Öfkeyi yönetmek","Nevevî 16 · Buhârî","Tekrarlanan bir öğüt olarak öfkenin kişiyi yönetmesine izin vermemeyi öne çıkarır.","Duygu geldiğinde davranışın otomatikleşmesini engelleyen kısa bir öz-denetim ilkesi sunar.","Öfkelendiğinde ilk 30 saniyede ne yaparsan zarar azalıyor?","Bugün öfke yükselirse cevap vermeden önce kısa bir ara ver.",["Hadis duygunun hiç oluşmamasını değil, öfkenin kontrolsüz davranışa dönüşmemesini hedefler.","Sürekli yoğun öfke ilişkileri veya güvenliği etkiliyorsa yalnız manevî tavsiye değil, profesyonel destek de gerekebilir."]),
  u(17,"Her işte ihsan","Nevevî 17 · Müslim","İhsanı, yani işi güzel ve merhametli yapmayı geniş bir ilke olarak ortaya koyar; hayvana eziyeti azaltma örneği verir.","İbadet dışındaki işlerde de kalite, merhamet ve özen aramayı öğretir.","Bugün yaptığın sıradan bir işi daha özenli hâle nasıl getirebilirsin?","Bir işi acele bitirmek yerine tek bir ayrıntısını daha iyi yap.",["İhsan, yalnız estetik güzellik değil; sorumluluğu hakkıyla ve mümkün olan en az zararla yerine getirmeyi de içerir.","Rivayetteki kesim örneği, hayvana acıyı azaltma sorumluluğunu özellikle görünür kılar."]),
  u(18,"Takva, telafi ve güzel ahlâk","Nevevî 18 · Tirmizî","Her durumda Allah’a karşı sorumluluk bilinci, hatanın ardından iyilikle telafi ve insanlara güzel davranış öğütlenir.","Hata yaptıktan sonra “artık bitti” demek yerine onarıcı davranış geliştirmeyi öğretir.","Son bir hatanı düzeltmek için atabileceğin en küçük telafi adımı ne?","Bir hatanın ardından bugün somut bir iyilik yap.",["İyilik yapmak hukuki veya kişisel hak ihlalini otomatik silmez; gerekiyorsa özür, iade veya telafi de gerekir.","Güzel ahlâk, manevî programın sosyal yüzüdür; motor bunu puanlamaz, yalnız davranış hedefi olarak hatırlatabilir."]),
  u(19,"Allah’ı gözetmek ve tevekkül","Nevevî 19 · Tirmizî","Allah’ın sınırlarını gözetmek, dua ve yardım talebinde O’na yönelmek, kader ve sabır bilinci üzerine yoğunlaşan öğütler içerir.","Kaygı ile tevekkülü birbirine karıştırmadan, sorumluluk alıp sonucu Allah’a bırakma dengesini düşünmeye çağırır.","Kontrol edebildiğin şey ile edemediğin şeyi bugün nasıl ayırabilirsin?","Kontrolündeki bir işi yap; sonucuyla ilgili aşırı tekrar düşünmeyi bırakmayı dene.",["Tevekkül tedbiri bırakmak değildir; sebeplere başvurup sonucu Allah’a havale etme anlayışıyla birlikte ele alınır.","Kader konusu yine akaid müfredatına bağlanmalıdır; kısa bir hadis tek başına tüm ayrıntıları açıklamaz."]),
  u(20,"Hayâ ve iç sınır","Nevevî 20 · Buhârî","Hayâ duygusunun insan davranışını sınırlandıran eski ve köklü bir peygamberlik mirası olduğuna işaret eder.","Dış denetim yokken de kişiye içsel bir ahlâk filtresi kazandıran kavramı tanıtır.","Kimse görmese de yapmamayı tercih ettiğin bir davranışın ölçüsü ne?","Bugün bir davranışı yalnız “yakalanır mıyım?” değil “doğru mu?” diye değerlendir.",["Hayâ, kişiyi meşru haktan veya gerekli sorudan alıkoyan utangaçlıkla aynı şey değildir.","Olumlu hayâ, insanın değeri ve sorumluluğuyla uyumlu bir iç sınırdır."]),
  u(21,"İman ve istikamet","Nevevî 21 · Müslim","İman ikrarından sonra istikamet, yani doğru çizgide sebat etme çağrısı yapan çok kısa ve yoğun bir rivayettir.","Manevî Rota’nın “az ama sürekli” yaklaşımını doğrudan destekleyen temel kavramlardan biridir.","Sende en çok hangi küçük davranış istikrar istiyor?","Bugün yeni bir hedef eklemek yerine mevcut bir küçük hedefi koru.",["İstikamet mükemmellik değil, yönü koruyup sapınca geri dönebilmektir.","Bu yüzden motor bir kötü günü kimlik etiketi yapmaz; geri dönüşü planın parçası kabul eder."]),
  u(22,"Farzları korumak ve helal-haram sınırı","Nevevî 22 · Müslim","Farz namazlar, Ramazan orucu ve helal-haram sınırını koruma üzerinden temel sorumlulukların önemini anlatır.","Başlangıçta çok nafile hedef eklemeden önce temel yükümlülüklerin yerini bilmeyi hatırlatır.","Programında temel olanla ek olanı bugün ayırabiliyor musun?","Ek hedeflerden önce bir temel sorumluluğu daha dikkatli yap.",["Rivayet, dinî hayatın yalnız gönüllü aktivitelerden oluşmadığını; farzların merkezde olduğunu gösterir.","Kişinin özel fıkhî soruları için mezhep ve durumuna uygun kaynak gerekebilir."]),
  u(23,"Temizlik, zikir, sabır ve Kur’an","Nevevî 23 · Müslim","Temizlik, hamd, namaz, sadaka, sabır ve Kur’an gibi birçok kulluk unsurunu kısa bir bütün içinde ilişkilendirir.","Manevî gelişimin tek bir alışkanlığa indirgenemeyeceğini; farklı alanların birbirini desteklediğini gösterir.","Şu an rotanda güçlü olan alan hangisi, ihmal ettiğin alan hangisi?","Bugün güçlü rutinin yanında yalnız bir küçük dengeleyici adım ekle.",["Hadisin “Kur’an lehine veya aleyhine delildir” vurgusu, bilgi ile amel arasındaki bağ üzerine düşünmeye açılır.","Sabır burada pasiflik değil, doğru davranışta dayanıklılık anlamıyla birlikte okunmalıdır."]),
  u(24,"Zulümden sakınmak ve Allah’a muhtaçlık","Nevevî 24 · Müslim (kudsî hadis)","Zulüm yasağı, hidayet, rızık, bağışlanma ve kulun Allah’a muhtaçlığı üzerinde duran kapsamlı bir kudsî hadistir.","Hem başkasına haksızlık yapmama hem de ihtiyaçlarını Allah’tan isteme bilincini birlikte kurar.","Bugün birine karşı haksızlık ihtimali taşıyan bir tutumun var mı?","Bir hakkı düzelt; ardından bir ihtiyacını dua ile açıkça Allah’a arz et.",["Zulüm yalnız fiziksel zarar değildir; hak ihlali, haksızlık ve değersizleştirme gibi geniş alanları kapsar.","Kudsî hadis, Allah’ın mutlak zenginliği ile kulun ihtiyaç hâlini güçlü biçimde karşılaştırır."]),
  u(25,"Günlük hayatın sadakaya dönüşmesi","Nevevî 25 · Müslim","Zikirden iyiliği teşvike ve helal aile hayatına kadar birçok davranışın doğru niyetle sevap alanına dönüşebileceğini gösterir.","Maneviyatı yalnız para vermeye veya belirli ritüellere sıkıştırmayan geniş bir iyilik anlayışı kazandırır.","Bugün zaten yaptığın hangi helal işi daha bilinçli niyetle yapabilirsin?","Sıradan bir işi fayda niyetiyle yap ve gün sonunda not et.",["Hadis, maddi imkânı sınırlı olan kişinin de iyilik kapılarının çok olduğunu gösterir.","Niyet, haram bir davranışı helale çevirmediği gibi; helal ve faydalı davranışın değerini yönlendirebilir."]),
  u(26,"Her gün küçük iyilikler","Nevevî 26 · Buhârî ve Müslim","Adalet, yardım, güzel söz, namaza yürümek ve yoldan eziyet vereni kaldırmak gibi gündelik iyilikleri sadaka kapsamında anar.","Büyük projeler beklemeden gün içindeki küçük fayda davranışlarını görünür kılar.","Bugün çevrene fayda veren en küçük davranış ne olabilir?","Bir kişiye işini kolaylaştıracak somut bir yardım yap.",["Sürdürülebilir ahlâk çoğu zaman küçük ve tekrar edilebilir davranışlarla kurulur.","Uygulama bu davranışları puanlamak yerine hatırlatıcı bir “bugünün küçük iyiliği” alanı olarak sunabilir."]),
  u(27,"İyilik, günah ve vicdanın işareti","Nevevî 27 · Müslim; Ahmed ve Dârimî rivayetleri","Güzel ahlâkı iyiliğin merkezine yerleştirir; günahın kalpte huzursuzluk doğurabilen yönüne işaret eder.","İçsel rahatsızlığın önemli bir sinyal olabileceğini, fakat hukukî hüküm için tek başına yeterli olmadığını ayırt etmeyi öğretir.","İç huzursuzluğun bilgi eksikliğinden mi, vicdan uyarısından mı geldiğini nasıl ayırırsın?","Bir konuda kalbin daralıyorsa önce kaynağı kontrol et, sonra güvenilir birine danış.",["“Kalbine danış” ifadesi açık nas ve hukukî bilgiye rağmen kişisel hisle hüküm üretmek anlamına gelmez.","Vicdan, sağlıklı eğitim ve doğru bilgiyle birlikte daha güvenilir bir ahlâk pusulasına dönüşür."]),
  u(28,"Sünnete bağlılık ve ihtilaf zamanı","Nevevî 28 · Ebû Dâvûd ve Tirmizî","Takva, sünnete bağlılık ve büyük ihtilaflar döneminde güvenilir çizgiyi koruma üzerine öğütler içerir.","Bilgi kirliliğinde her yeni iddiaya koşmak yerine sahih kaynak ve yerleşik usule tutunma alışkanlığı kazandırır.","Bir dinî tartışmada hangi kaynağı “temel referans” kabul edeceğini biliyor musun?","Bugün bir tartışma yerine güvenilir bir temel kaynağı 10 dakika oku.",["Rivayet, değişen her şeyin otomatik olarak dinî bidat olduğu anlamına gelmez; kavramın usul içindeki anlamı ayrıca çalışılmalıdır.","Başlangıç öğrencisi için en güvenli yaklaşım, tartışma kültürü yerine temel kaynak okuma disiplinidir."]),
  u(29,"İyilik kapıları ve dili korumak","Nevevî 29 · Tirmizî","Farzlar, oruç, sadaka, gece namazı ve özellikle dilin kontrolü üzerinden çok katmanlı bir iyilik haritası sunar.","İbadetleri sıralarken dil ve iletişim ahlâkının da merkezî bir sorumluluk olduğunu hatırlatır.","Dilinden çıkan hangi tür söz sana en çok zarar veriyor?","Bugün bir tartışmada son sözü söylemek yerine susmayı seç.",["Hadisin geniş yapısı, “çok özellik” değil “öncelik ve bütünlük” okumayı gerektirir.","Dil kontrolü, dijital ortamda yazılan mesaj ve yorumları da kapsayacak şekilde düşünülebilir."]),
  u(30,"Farzlar, sınırlar ve susulan alanlar","Nevevî 30 · Dârekutnî ve diğerleri","Farzları ihmal etmeme, sınırları aşmama, haramlardan sakınma ve hakkında hüküm bildirilmemiş alanlarda gereksiz zorlamadan kaçınma fikrini taşır.","Dinde kolaylık ile keyfîlik arasındaki çizgiyi; hüküm üretme ile susulan alana saygıyı ayırt etmeye yardım eder.","Bilmediğin bir konuda hemen kesin cevap verme eğilimin var mı?","Bugün bilmediğin bir dinî soruya “araştırmam gerekir” deme pratiği yap.",["Bu rivayetin hadis derecesi ve yorumları şerh kaynaklarında ayrıca ele alınır; başlangıç rotası bunu kesin hüküm üretme aracı yapmaz.","Usul bilinci, hem aşırı katılığı hem de ölçüsüz gevşekliği azaltır."]),
  u(31,"Zühd ve insanlarda olana göz dikmemek","Nevevî 31 · İbn Mâce ve diğerleri","Dünyaya aşırı bağlanmamak ve insanların elindekine göz dikmemek üzerinden Allah sevgisi ve insanlar arası ilişkiler için bir ölçü sunar.","Tüketim, kıyas ve beklenti baskısını azaltan bir iç bağımsızlık fikri verir.","Başkalarının sahip olduğu şeylerle kıyas sana nerede yük oluyor?","Bugün bir kıyas tetikleyicisini azalt ve sahip olduğun bir nimeti yaz.",["Zühd dünyayı terk etmek değil; dünyanın kalpte mutlak amaç hâline gelmemesi şeklinde anlaşılır.","İnsanlardan beklentiyi azaltmak, yardımlaşmayı reddetmek değil; bağımlı kıyas ve tamahı azaltmaktır."]),
  u(32,"Zarar verme ve zararla karşılık vermeme","Nevevî 32 · İbn Mâce, Dârekutnî ve Muvatta rivayetleri","Kişinin kendisine veya başkasına haksız zarar vermemesi ve zarara zararla karşılık verme döngüsüne girmemesi yönünde temel bir hukuk/ahlâk ilkesi sunar.","Birçok fıkhî kaidenin arkasındaki zarar azaltma mantığını tanımaya yardımcı olur.","Bir kararın başkasına gereksiz zarar verip vermediğini nasıl kontrol edebilirsin?","Bugün bir konuda “en az zarar veren seçenek hangisi?” diye düşün.",["Zarar kavramı fıkıhta teknik ayrıntılara sahiptir; her rahatsızlık “hukukî zarar” sayılmaz.","Bu hadis, bireysel öç alma değil; zararı önleme ve adil çözüm arama yönünde okunmalıdır."]),
  u(33,"İddia, delil ve ispat yükü","Nevevî 33 · Beyhakî; bir kısmı Buhârî ve Müslim’de","Bir iddiayı ileri sürenin delil getirmesi, inkâr eden tarafın ise usule göre yeminle muhatap olması şeklindeki temel ispat prensibini anlatır.","Dinî veya dünyevî bir iddiayı kanıtsız kabul etmeme alışkanlığını güçlendirir.","Bugün duyduğun güçlü bir iddianın delili gerçekten var mı?","Bir iddiayı paylaşmadan önce birincil kaynağını bul.",["Hadis, hukukta iddia ve ispat düzeninin keyfî suçlamaları sınırlama işlevini gösterir.","Gündelik bilgi okuryazarlığında da “kanıt yükü kimde?” sorusu son derece değerlidir."]),
  u(34,"Yanlışa karşı sorumluluk ve güç yetirme","Nevevî 34 · Müslim","Yanlışla karşılaşıldığında kişinin yetkisi ve gücü ölçüsünde uygun yolla tepki vermesi; en azından kalben reddetmesi gerektiğini anlatır.","Sorumluluk ile yetkiyi ayırmayı ve gelişigüzel müdahale yerine bilgi, hikmet ve meşru yöntem aramayı öğretir.","Bir yanlışa müdahale ederken yetkin, bilgin ve muhtemel sonuçların yeterli mi?","Bugün bir yanlışı düzeltmek istiyorsan önce en güvenli ve yetkili yolu belirle.",["Bu hadis bireysel zor kullanma yetkisi vermez; “el ile değiştirme” konusu klasik şerhlerde yetki ve güç şartlarıyla ele alınır.","Yanlışı düzeltme girişimi daha büyük zarar doğuracaksa usul ve ehliyet değerlendirmesi gerekir."]),
  u(35,"Kardeşlik, haysiyet ve takva","Nevevî 35 · Müslim","Haset, kin, küçümseme ve haksız rekabetten sakındırır; Müslümanın can, mal ve onur dokunulmazlığını vurgular.","Manevî gelişimin sosyal haysiyet ve kardeşlik hukukuyla ölçülebilir davranışlara dönüşmesini sağlar.","Başkalarını küçümseme veya kıyas dili sende nerede ortaya çıkıyor?","Bugün bir kişiye karşı içten bir iyi niyet ve saygı davranışı göster.",["Takvanın kalple ilişkisi, dış görünüş üzerinden başkasının maneviyatını derecelendirmemeyi hatırlatır.","Bu, uygulamada “iman puanı” veya kullanıcılar arası maneviyat sıralaması yapmama ilkemizi de destekler."]),
  u(36,"Sıkıntıyı gidermek ve ilim yoluna çıkmak","Nevevî 36 · Müslim","Birinin sıkıntısını hafifletme, borçluya kolaylık, kusuru örtme, yardımlaşma ve ilim yolunda yürümenin faziletini bir araya getirir.","İlim öğrenmeyi bireysel prestij değil, yardım ve toplumsal fayda içinde konumlandırır.","Öğrendiğin bilgi bugün kimin işini kolaylaştırabilir?","Bir kişiye somut kolaylık sağla veya öğrendiğin faydalı bir bilgiyi uygun biçimde paylaş.",["İlim yolunun fazileti, yalnızca bilgi biriktirmeye değil, niyet ve faydaya bağlanır.","Kusuru örtmek, suç veya devam eden zararı gizlemek anlamına gelmez; güvenlik ve hukuk gerektiren durumlar ayrıdır."]),
  u(37,"Niyet ve amelin yazılması","Nevevî 37 · Buhârî ve Müslim (kudsî hadis)","İyi niyetin ve yapılan iyiliğin karşılığı; kötülük niyeti ile fiil arasındaki fark üzerinden ilahî lütuf ve adalet anlatılır.","Niyetin değerini yeniden gösterirken yalnız düşüncenin değil fiile dönüşen davranışın da önemini dengeler.","İyi niyet olarak kalıp davranışa dönüşmeyen bir hedefin var mı?","Bugün uzun süredir niyet ettiğin küçük bir iyiliği fiile çevir.",["Niyet ve davranış ilişkisi, kişinin kendini yalnız “iyi düşünüyorum” diyerek değerlendirmemesi gerektiğini hatırlatır.","Hadisin anlatımı Allah’ın rahmet ve lütfunun genişliğini de öne çıkarır."]),
  u(38,"Farzlarla yakınlaşmak, nafilelerle derinleşmek","Nevevî 38 · Buhârî (kudsî hadis)","Allah’a en sevgili yakınlaşmanın farzlarla başladığını, nafilelerin ise bunun üzerine sürdürülen bir yakınlık yolu olduğunu anlatır.","Manevî programda farzları ihmal edip çok sayıda ek görev biriktirmeme ilkesini güçlendirir.","Programında farz ile nafile arasındaki öncelik sırası net mi?","Bugün ek bir hedef koymadan önce temel sorumluluğunu daha dikkatli yap.",["Hadisin “Allah’ın sevgisi” anlatımı, kulun iradesini ilahî rızaya göre yönlendirmesi bağlamında şerh edilir.","Bu rota, nafileleri temel sorumlulukların yerine geçen performans puanları gibi kullanmaz."]),
  u(39,"Hata, unutma ve zorlanma hâli","Nevevî 39 · İbn Mâce ve Beyhakî","Hata, unutma ve zorla yaptırılma durumlarının sorumluluk değerlendirmesinde özel yeri bulunduğunu ifade eden rivayetlerden biridir.","Dinî sorumlulukta niyet, irade ve güç yetirme gibi unsurların önemini fark ettirir.","Bir hatayı bilinçli tercih ile istemeden yapılan yanlıştan ayırabiliyor musun?","Bugün bir hatada kendini veya başkasını değerlendirirken niyet ve şartları da hesaba kat.",["Fıkhî sonuçlar meseleye göre değişebilir; bu hadis tek başına her hukukî sonucu belirlemez.","Başlangıç öğrencisi için ana ders, sorumluluk değerlendirmesinin bağlam ve iradeyi de içerdiğidir."]),
  u(40,"Dünyada yolcu gibi olmak","Nevevî 40 · Buhârî","Dünyada kalıcılık vehmine kapılmadan yolcu bilinciyle yaşamak, zamanı ve sağlığı fırsat bilmek üzerine yoğunlaşır.","Erteleme alışkanlığını azaltır ve uzun hedefleri bugünün küçük adımına bağlar.","Bugün “sonra yaparım” dediğin hangi değerli işi küçük de olsa başlatabilirsin?","Sağlığın ve vaktin elverirken 10 dakikalık değerli bir işi şimdi yap.",["Yolculuk benzetmesi dünyadaki sorumlulukları terk etmek değil, onları nihai amaç hâline getirmemek anlamında okunur.","Zaman farkındalığı, uygulamadaki günlük küçük rota yaklaşımının temel motivasyonlarından biridir."]),
  u(41,"Arzuyu vahyin ölçüsüne göre eğitmek","Nevevî 41 · Kitâbü’l-Hücce rivayeti","Kişisel arzu ve eğilimlerin, Peygamber’in getirdiği rehberlikle çatıştığında ölçünün vahiy ve sünnet olması gerektiği fikrini öne çıkarır.","“İstiyorum” ile “doğru” arasındaki farkı düşünmeye ve hevanın bilgi yerine geçmemesine yardım eder.","Bir konuda tercihini delilden önce savunuyor olabileceğin oluyor mu?","Bugün güçlü görüş taşıdığın bir konuda karşı delili de dürüstçe oku.",["Bu rivayetin isnadı hakkında hadis âlimleri arasında değerlendirmeler bulunduğu için kaynak notuyla birlikte okunmalıdır.","Ana eğitim ilkesi, arzunun tek başına dinî ölçü hâline gelmemesidir; bunun için sahih kaynak ve usul gerekir."]),
  u(42,"Ümit, istiğfar ve tevhid","Nevevî 42 · Tirmizî (kudsî hadis)","Dua, ümit, istiğfar ve şirkten uzak tevhid üzere Allah’a yönelmenin geniş bağışlanma umuduyla ilişkisini anlatır.","Uzun bir öğrenme yolculuğunu korku veya başarı baskısıyla değil, ümit ve dönüş kapısıyla tamamlar.","Hata sonrası umutsuzluğa mı, samimi dönüşe mi daha kolay yöneliyorsun?","Bugün kısa bir istiğfar ve dua ile yeni bir başlangıç yap.",["Ümit, hatayı hafife almak değil; tövbe ve dönüş kapısının açık olduğunu bilmektir.","Koleksiyonun sonunda bu hadis, ilim yolunun hedefinin kusursuz görünmek değil; doğruyu arayıp hatada geri dönebilmek olduğunu hatırlatır."])
];

export const KIRK_HADIS_TR={
1:`Müminlerin emiri Ebû Hafs Ömer b. Hattâb (r.a.) şöyle dedi: Resûlullah’ı (s.a.v.) şöyle buyururken işittim: “Ameller ancak niyetlere göredir. Herkese ancak niyet ettiği vardır. Kimin hicreti Allah’a ve Resûlü’ne ise onun hicreti Allah’a ve Resûlü’nedir. Kimin hicreti elde edeceği bir dünyalık veya evleneceği bir kadın için ise onun hicreti de hicret ettiği şeyedir.”`,
2:`Ömer (r.a.) şöyle anlattı: Bir gün Resûlullah’ın (s.a.v.) yanında otururken, elbisesi bembeyaz, saçı simsiyah bir adam çıkageldi. Üzerinde yolculuk izi yoktu ve içimizden kimse onu tanımıyordu. Peygamber’in yanına oturdu; dizlerini onun dizlerine dayadı, ellerini uyluklarının üzerine koydu ve: “Ey Muhammed, bana İslâm’ı anlat” dedi. Resûlullah: “İslâm; Allah’tan başka ilâh olmadığına ve Muhammed’in Allah’ın elçisi olduğuna şahitlik etmen, namazı kılman, zekâtı vermen, Ramazan orucunu tutman ve gücün yetiyorsa Beyt’i haccetmendir” buyurdu. Adam: “Doğru söyledin” dedi. Hem sorup hem doğrulamasına şaşırdık. Sonra: “Bana imanı anlat” dedi. Resûlullah: “Allah’a, meleklerine, kitaplarına, peygamberlerine, âhiret gününe ve hayrıyla şerriyle kadere iman etmendir” buyurdu. Adam: “Doğru söyledin. Bana ihsanı anlat” dedi. Resûlullah: “Allah’a, O’nu görüyormuşçasına kulluk etmendir; sen O’nu görmesen de O seni görür” buyurdu. Adam: “Kıyametin ne zaman kopacağını anlat” dedi. Resûlullah: “Bu konuda kendisine soru sorulan, sorandan daha bilgili değildir” buyurdu. Adam: “Öyleyse alametlerini anlat” dedi. Resûlullah: “Cariyenin kendi efendisini doğurması ve yalınayak, çıplak, yoksul koyun çobanlarının bina yükseltmekte yarıştıklarını görmendir” buyurdu. Sonra adam gitti. Bir süre sonra Resûlullah bana: “Ey Ömer, soru soranın kim olduğunu biliyor musun?” dedi. “Allah ve Resûlü daha iyi bilir” dedim. “O Cebrâil’di; size dininizi öğretmek için geldi” buyurdu.`,
3:`Abdullah b. Ömer (r.a.) şöyle dedi: Resûlullah’ı (s.a.v.) şöyle buyururken işittim: “İslâm beş esas üzerine kurulmuştur: Allah’tan başka ilâh olmadığına ve Muhammed’in Allah’ın elçisi olduğuna şahitlik etmek, namazı kılmak, zekâtı vermek, Beyt’i haccetmek ve Ramazan orucunu tutmak.”`,
4:`Abdullah b. Mes‘ûd (r.a.) şöyle dedi: Doğru söyleyen ve doğruluğu tasdik edilmiş olan Resûlullah (s.a.v.) bize şöyle anlattı: “Sizden her birinizin yaratılışı annesinin karnında kırk gün nutfe olarak toplanır; sonra bunun gibi bir süre alaka, sonra bunun gibi bir süre mudğa olur. Ardından ona bir melek gönderilir; ruh üflenir ve meleğe dört şey yazması emredilir: rızkı, eceli, ameli ve bahtiyar mı bedbaht mı olacağı. Kendisinden başka ilâh olmayan Allah’a yemin olsun ki sizden biri cennet ehlinin amelini işler; onunla cennet arasında bir arşın kadar mesafe kalır, fakat hakkında yazılan öne geçer ve cehennem ehlinin amelini işler de oraya girer. Yine sizden biri cehennem ehlinin amelini işler; onunla cehennem arasında bir arşın kadar mesafe kalır, fakat hakkında yazılan öne geçer ve cennet ehlinin amelini işler de oraya girer.”`,
5:`Müminlerin annesi Âişe (r.a.) şöyle dedi: Resûlullah (s.a.v.) buyurdu ki: “Kim bizim bu işimizde ondan olmayan bir şeyi ortaya çıkarırsa o reddedilmiştir.” Müslim’in bir rivayetinde ise: “Kim bizim emrimize uygun olmayan bir amel işlerse o reddedilmiştir.”`,
6:`Nu‘mân b. Beşîr (r.a.) şöyle dedi: Resûlullah’ı (s.a.v.) şöyle buyururken işittim: “Helâl bellidir, haram da bellidir. Bu ikisi arasında insanların çoğunun hükmünü bilmediği şüpheli şeyler vardır. Kim şüpheli şeylerden sakınırsa dinini ve şerefini korumuş olur. Kim şüpheli şeylere düşerse harama düşer; tıpkı koruluğun çevresinde sürü otlatan çobanın oraya girivermesinin yakın olması gibi. Dikkat edin, her hükümdarın bir koruluğu vardır; Allah’ın koruluğu da haram kıldığı şeylerdir. Dikkat edin, bedende bir et parçası vardır; o iyi olursa bütün beden iyi olur, o bozulursa bütün beden bozulur. Dikkat edin, o kalptir.”`,
7:`Temîm ed-Dârî’den (r.a.) rivayet edildiğine göre Peygamber (s.a.v.) “Din nasihattir” buyurdu. “Kimin için?” diye sorduk. “Allah için, Kitabı için, Resûlü için, Müslümanların yöneticileri ve bütün Müslümanlar için” buyurdu.`,
8:`İbn Ömer’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “İnsanlarla, Allah’tan başka ilâh olmadığına ve Muhammed’in Allah’ın elçisi olduğuna şahitlik edinceye, namazı kılıncaya ve zekâtı verinceye kadar savaşmakla emrolundum. Bunları yaptıklarında, İslâm’ın hakkı dışında canlarını ve mallarını benden korumuş olurlar; hesapları ise Allah’a aittir.”`,
9:`Ebû Hüreyre (r.a.) şöyle dedi: Resûlullah’ı (s.a.v.) şöyle buyururken işittim: “Size neyi yasakladıysam ondan kaçının. Size neyi emrettiysem gücünüz yettiğince onu yapın. Sizden öncekileri, çok soru sormaları ve peygamberleri hakkında ihtilafa düşmeleri helâk etti.”`,
10:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Allah temizdir ve ancak temiz olanı kabul eder. Allah peygamberlere neyi emrettiyse müminlere de onu emretmiştir. ‘Ey peygamberler! Temiz ve helâl olanlardan yiyin ve salih amel işleyin’ buyurmuş; ‘Ey iman edenler! Size verdiğimiz rızıkların temiz olanlarından yiyin’ buyurmuştur.” Sonra uzun yolculuğa çıkmış, saçı başı dağınık, üstü başı tozlu bir adamı anlattı. Adam ellerini göğe kaldırıp “Rabbim, Rabbim!” diye dua ediyor; fakat yediği haram, içtiği haram, giydiği haram ve haramla beslenmiş. “Böyle birinin duasına nasıl karşılık verilsin?” buyurdu.`,
11:`Hasan b. Ali (r.a.) şöyle dedi: Resûlullah’tan (s.a.v.) şu sözü ezberledim: “Seni şüpheye düşüren şeyi bırak, şüpheye düşürmeyene yönel.”`,
12:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Kişinin kendisini ilgilendirmeyen şeyi terk etmesi, İslâm’ının güzelliğindendir.”`,
13:`Enes b. Mâlik’ten (r.a.) rivayet edildiğine göre Peygamber (s.a.v.) şöyle buyurdu: “Sizden biri kendisi için sevdiğini kardeşi için de sevmedikçe iman etmiş olmaz.”`,
14:`İbn Mes‘ûd’dan (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Allah’tan başka ilâh olmadığına ve benim Allah’ın elçisi olduğuma şahitlik eden bir Müslümanın kanı ancak şu üç durumdan biri sebebiyle hukukî olarak helâl olabilir: evli olduğu hâlde zina eden, cana karşı can ve dinini terk edip cemaatten ayrılan.”`,
15:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Allah’a ve âhiret gününe iman eden ya hayır söylesin ya sussun. Allah’a ve âhiret gününe iman eden komşusuna ikram etsin. Allah’a ve âhiret gününe iman eden misafirine ikram etsin.”`,
16:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre bir adam Peygamber’e (s.a.v.) “Bana öğüt ver” dedi. Peygamber: “Öfkelenme” buyurdu. Adam isteğini birkaç kez tekrarladı; Peygamber her defasında: “Öfkelenme” buyurdu.`,
17:`Şeddâd b. Evs’ten (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Allah her şeyde ihsanı gerekli kılmıştır. Öldürmek zorunda kaldığınızda öldürmeyi güzel ve usulüne uygun yapın; hayvan kestiğinizde kesimi güzel yapın. Sizden biri bıçağını iyice bilesin ve keseceği hayvana eziyet çektirmesin.”`,
18:`Ebû Zer Cündeb b. Cünâde ve Ebû Abdurrahman Muâz b. Cebel’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Nerede olursan ol Allah’a karşı takvâlı ol. Kötülüğün ardından bir iyilik yap ki onu silsin. İnsanlara güzel ahlâkla davran.”`,
19:`Abdullah b. Abbas (r.a.) şöyle anlattı: Bir gün Peygamber’in (s.a.v.) arkasındaydım. Bana şöyle buyurdu: “Yavrucuğum, sana bazı sözler öğreteyim: Allah’ın hududunu koru ki Allah da seni korusun. Allah’ı gözet ki O’nu önünde bulasın. İstediğin zaman Allah’tan iste; yardım dilediğin zaman Allah’tan yardım dile. Bil ki bütün insanlar sana bir fayda vermek için toplansalar, Allah’ın senin için yazdığından başka bir fayda veremezler. Sana zarar vermek için toplansalar, Allah’ın senin aleyhine yazdığından başka bir zarar veremezler. Kalemler kaldırılmış, sayfalar kurumuştur.” Başka bir rivayette: “Allah’ı gözet, O’nu karşında bulursun. Rahatlık zamanında Allah’ı tanı ki sıkıntı zamanında O da seni gözetip yardım etsin. Bil ki seni ıskalayan şey sana isabet edecek değildi; sana isabet eden şey de seni ıskalayacak değildi. Bil ki zafer sabırla, ferahlık sıkıntıyla, kolaylık da zorlukla beraberdir.”`,
20:`Ebû Mes‘ûd Ukbe b. Amr el-Ensârî’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “İnsanların önceki peygamberlerden beri aktara geldiği sözlerden biri şudur: Utanmazsan dilediğini yap.”`,
21:`Süfyân b. Abdullah es-Sekafî (r.a.) şöyle dedi: “Ey Allah’ın Resûlü! İslâm hakkında bana öyle bir söz söyle ki senden sonra bu konuda başka kimseye soru sormaya ihtiyaç duymayayım.” Resûlullah (s.a.v.): “Allah’a iman ettim de, sonra dosdoğru ol” buyurdu.`,
22:`Câbir b. Abdullah’tan (r.a.) rivayet edildiğine göre bir adam Resûlullah’a (s.a.v.) şöyle sordu: “Farz namazları kılsam, Ramazan orucunu tutsam, helâli helâl kabul edip haramdan uzak dursam ve bunlara başka bir şey eklemesem cennete girer miyim?” Resûlullah: “Evet” buyurdu.`,
23:`Ebû Mâlik el-Eş‘arî’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Temizlik imanın yarısıdır. ‘Elhamdülillah’ mizanı doldurur. ‘Sübhânallah’ ve ‘Elhamdülillah’ göklerle yer arasını doldurur. Namaz bir nurdur. Sadaka bir delildir. Sabır bir ışıktır. Kur’an senin lehine veya aleyhine bir hüccettir. Her insan sabahleyin çıkar ve nefsini satışa çıkarır; kimi onu kurtarır, kimi de helâke sürükler.”`,
24:`Ebû Zer’den (r.a.) rivayet edildiğine göre Peygamber (s.a.v.), Allah Teâlâ’nın şöyle buyurduğunu nakletti: “Ey kullarım! Ben zulmü kendime haram kıldım ve onu sizin aranızda da haram kıldım; öyleyse birbirinize zulmetmeyin. Ey kullarım! Benim hidayet verdiklerim dışında hepiniz yolunu şaşırabilirsiniz; benden hidayet isteyin ki sizi doğru yola ileteyim. Ey kullarım! Benim doyurduklarım dışında hepiniz açsınız; benden yiyecek isteyin ki sizi doyurayım. Ey kullarım! Benim giydirdiklerim dışında hepiniz çıplaksınız; benden giyim isteyin ki sizi giydireyim. Ey kullarım! Gece gündüz hata işlersiniz; ben bütün günahları bağışlarım; benden bağışlanma dileyin ki sizi bağışlayayım. Ey kullarım! Bana zarar verecek güce ulaşamazsınız ki zarar veresiniz; bana fayda verecek güce de ulaşamazsınız ki fayda veresiniz. Ey kullarım! İlk insanınızdan son insanınıza, insanlarınızdan cinlerinize kadar hepiniz en takvâlı bir kişinin kalbi gibi olsanız, bu benim mülkümde hiçbir artış meydana getirmez. Hepiniz en günahkâr bir kişinin kalbi gibi olsanız da mülkümden hiçbir şey eksiltmez. Ey kullarım! Hepiniz bir düzlükte toplanıp benden isteseniz ve ben her birinize istediğini versem, bu benim katımdakinden, denize batırılan bir iğnenin denizden eksilttiğinden fazla eksiltmez. Ey kullarım! Bunlar sizin amellerinizdir; onları sizin için sayar, sonra karşılığını eksiksiz veririm. Kim hayır bulursa Allah’a hamd etsin; kim başka bir şey bulursa yalnız kendisini kınasın.”`,
25:`Ebû Zer’den (r.a.) rivayet edildiğine göre Peygamber’in (s.a.v.) ashabından bazı yoksullar: “Ey Allah’ın Resûlü! Zenginler sevapların hepsini götürdüler. Bizim kıldığımız gibi namaz kılıyor, bizim tuttuğumuz gibi oruç tutuyor ve mallarının fazlasından sadaka veriyorlar” dediler. Resûlullah şöyle buyurdu: “Allah sizin için de sadaka vereceğiniz şeyler kılmadı mı? Her ‘Sübhânallah’ sadakadır, her ‘Allahu ekber’ sadakadır, her ‘Elhamdülillah’ sadakadır, her ‘Lâ ilâhe illallah’ sadakadır; iyiliği emretmek sadakadır, kötülükten sakındırmak sadakadır. Hatta sizden birinin eşiyle helâl ilişkisi de sadakadır.” “Ey Allah’ın Resûlü, insan şehvetini giderir de bundan sevap mı kazanır?” dediler. “Onu haram yoldan giderseydi günah olmaz mıydı? İşte helâl yoldan giderdiğinde de sevap vardır” buyurdu.`,
26:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “İnsanların her eklemi için güneşin doğduğu her gün sadaka gerekir. İki kişinin arasını adaletle düzeltmen sadakadır. Bir kimseye bineğine binmesinde yardım etmen veya yükünü bineğine kaldırman sadakadır. Güzel bir söz sadakadır. Namaza giderken attığın her adım sadakadır. Yoldan eziyet veren şeyi kaldırman da sadakadır.”`,
27:`Nevvâs b. Sem‘ân’dan (r.a.) rivayet edildiğine göre Peygamber (s.a.v.) şöyle buyurdu: “İyilik güzel ahlâktır. Günah ise içinde huzursuzluk uyandıran ve insanların bilmesini istemediğin şeydir.” Vâbisa b. Ma‘bed (r.a.) şöyle anlattı: Resûlullah’a geldim. Bana: “İyilik hakkında sormaya mı geldin?” dedi. “Evet” dedim. “Kalbine danış. İyilik, nefsin ve kalbin huzur bulduğu şeydir. Günah ise insanlar sana fetva üstüne fetva verseler bile, içinde tereddüt uyandıran ve gönlünde gelip giden şeydir” buyurdu.`,
28:`İrbâd b. Sâriye (r.a.) şöyle dedi: Resûlullah (s.a.v.) bize öyle etkili bir öğüt verdi ki kalpler ürperdi, gözler yaşardı. “Ey Allah’ın Resûlü, bu sanki veda eden birinin öğüdü; bize tavsiyede bulun” dedik. Şöyle buyurdu: “Size Allah’a karşı takvâyı, başınıza bir köle bile yönetici olarak getirilse meşru olanı dinleyip itaati tavsiye ederim. Sizden uzun yaşayanlar birçok ihtilaf görecektir. O hâlde benim sünnetime ve doğru yolda olan râşid halifelerin sünnetine sarılın; ona azı dişlerinizle sımsıkı tutunun. Sonradan ortaya çıkarılan dinî işlerden sakının; çünkü dinde sonradan ortaya çıkarılan her şey sapmaya götürür.”`,
29:`Muâz b. Cebel (r.a.) şöyle dedi: “Ey Allah’ın Resûlü! Beni cennete sokacak ve cehennemden uzaklaştıracak bir amel söyle” dedim. Resûlullah: “Çok büyük bir şey sordun; fakat Allah’ın kolaylaştırdığı kimse için kolaydır: Allah’a kulluk eder, O’na hiçbir şeyi ortak koşmazsın; namazı kılar, zekâtı verir, Ramazan orucunu tutar, Beyt’i haccedersin.” Sonra: “Sana hayır kapılarını göstereyim mi? Oruç kalkandır. Sadaka suyun ateşi söndürdüğü gibi günahı söndürür. Bir de insanın gecenin ortasında kıldığı namaz...” buyurdu ve secde sûresinden ayetler okudu. Sonra: “Sana bu işin başını, direğini ve zirvesini haber vereyim mi?” dedi. “Evet, ey Allah’ın Resûlü” dedim. “İşin başı İslâm, direği namaz, zirvesi cihaddır” buyurdu. Sonra: “Bunların hepsini kontrol altında tutan şeyi söyleyeyim mi?” dedi. “Evet” dedim. Dilini tuttu ve: “Şuna sahip ol” buyurdu. “Ey Allah’ın Peygamberi! Konuştuklarımızdan da hesaba çekilecek miyiz?” dedim. “Annen seni kaybetsin ey Muâz! İnsanları yüzüstü veya burunları üzerine ateşe sürükleyen, dillerinin biçtiklerinden başka nedir?” buyurdu.`,
30:`Ebû Sa‘lebe el-Huşenî’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Allah birtakım farzlar koymuştur; onları zayi etmeyin. Sınırlar belirlemiştir; onları aşmayın. Bazı şeyleri haram kılmıştır; onları çiğnemeyin. Bazı şeyler hakkında ise unuttuğu için değil, size rahmetinden dolayı susmuştur; onları didikleyip durmayın.”`,
31:`Sehl b. Sa‘d es-Sâidî (r.a.) şöyle dedi: Bir adam Peygamber’e (s.a.v.) gelip: “Ey Allah’ın Resûlü! Bana öyle bir amel göster ki onu yaptığımda hem Allah beni sevsin hem insanlar beni sevsin” dedi. Resûlullah: “Dünyaya karşı zahid ol ki Allah seni sevsin; insanların elindekine göz dikme ki insanlar seni sevsin” buyurdu.`,
32:`Ebû Saîd el-Hudrî’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Zarar vermek de yoktur, zarara zararla karşılık vermek de.”`,
33:`İbn Abbas’tan (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “İnsanlara sırf iddiaları üzerine istedikleri verilseydi, birtakım kimseler başkalarının malları ve canları üzerinde iddiada bulunurdu. Delil iddia edene, yemin ise inkâr edene aittir.”`,
34:`Ebû Saîd el-Hudrî (r.a.) şöyle dedi: Resûlullah’ı (s.a.v.) şöyle buyururken işittim: “Sizden kim bir kötülük görürse onu eliyle değiştirsin; buna gücü yetmezse diliyle; buna da gücü yetmezse kalbiyle karşı çıksın. Bu, imanın en zayıf derecesidir.”`,
35:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Birbirinize haset etmeyin, fiyat artırmak için sahte müşteri gibi davranmayın, birbirinize kin tutmayın, birbirinize sırt çevirmeyin; biriniz diğerinin alışverişi üzerine alışveriş yapmasın. Ey Allah’ın kulları, kardeş olun. Müslüman Müslümanın kardeşidir; ona zulmetmez, onu yardımsız bırakmaz, ona yalan söylemez ve onu küçümsemez. Takvâ buradadır” diyerek üç kez göğsünü işaret etti. “Bir kimseye Müslüman kardeşini küçümsemesi kötülük olarak yeter. Müslümanın kanı, malı ve onuru diğer Müslümana haramdır.”`,
36:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Peygamber (s.a.v.) şöyle buyurdu: “Kim bir müminin dünya sıkıntılarından birini giderirse Allah da onun kıyamet günündeki sıkıntılarından birini giderir. Kim darda olana kolaylık gösterirse Allah da ona dünyada ve âhirette kolaylık gösterir. Kim bir Müslümanın ayıbını örterse Allah da onun ayıbını dünyada ve âhirette örter. Kul kardeşinin yardımında olduğu sürece Allah da kulun yardımındadır. Kim ilim aramak için bir yola girerse Allah ona cennete giden yolu kolaylaştırır. Bir topluluk Allah’ın evlerinden birinde toplanır, Allah’ın kitabını okur ve aralarında onu müzakere ederse üzerlerine huzur iner, rahmet onları kuşatır, melekler onları çevreler ve Allah onları kendi katındakilere anar. Ameli kendisini geri bırakan kimseyi soyu ileri götüremez.”`,
37:`İbn Abbas’tan (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.), Rabbinden naklederek şöyle buyurdu: “Allah iyilikleri ve kötülükleri yazmış, sonra bunları açıklamıştır. Kim bir iyilik yapmaya niyet eder de yapamazsa Allah onu kendi katında tam bir iyilik olarak yazar. Niyet edip yaparsa onu on iyilikten yedi yüz kata, hatta daha fazlasına kadar yazar. Kim bir kötülük yapmaya niyet eder de yapmazsa Allah onu kendi katında tam bir iyilik olarak yazar. Niyet edip kötülüğü yaparsa onu yalnız bir kötülük olarak yazar.”`,
38:`Ebû Hüreyre’den (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) Allah Teâlâ’nın şöyle buyurduğunu bildirdi: “Kim benim bir velî kuluma düşmanlık ederse ona savaş ilan ederim. Kulum bana, kendisine farz kıldığım şeylerden daha sevimli hiçbir şeyle yaklaşamaz. Kulum nafilelerle bana yaklaşmaya devam eder; sonunda onu severim. Onu sevdiğimde işittiği kulağı, gördüğü gözü, tuttuğu eli ve yürüdüğü ayağı olurum. Benden isterse mutlaka veririm; bana sığınırsa mutlaka korurum.”`,
39:`İbn Abbas’tan (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Allah, ümmetimden hata ile yapılanı, unutularak yapılanı ve zorla yaptırılanı bağışlamıştır.”`,
40:`İbn Ömer (r.a.) şöyle dedi: Resûlullah (s.a.v.) omzumdan tuttu ve: “Dünyada bir yabancı yahut yolcu gibi ol” buyurdu. İbn Ömer de şöyle derdi: “Akşama çıktığında sabahı bekleme; sabaha çıktığında akşamı bekleme. Sağlığından hastalığın için, hayatından ölümün için pay ayır.”`,
41:`Abdullah b. Amr b. Âs’tan (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) şöyle buyurdu: “Sizden birinin arzusu ve eğilimi, benim getirdiğim şeye tâbi olmadıkça imanı kemale ermez.”`,
42:`Enes b. Mâlik’ten (r.a.) rivayet edildiğine göre Resûlullah (s.a.v.) Allah Teâlâ’nın şöyle buyurduğunu bildirdi: “Ey Âdemoğlu! Sen bana dua edip benden ümit ettiğin sürece, senden ne çıkmış olursa olsun seni bağışlarım ve buna aldırmam. Ey Âdemoğlu! Günahların göğün bulutlarına kadar ulaşsa, sonra benden bağışlanma dilesen seni bağışlarım. Ey Âdemoğlu! Bana yeryüzünü dolduracak kadar günahla gelsen, fakat bana hiçbir şeyi ortak koşmadan kavuşsan, ben de sana yeryüzünü dolduracak kadar bağışlanmayla gelirim.”`
};

for(const item of KIRK_HADIS_UNITS)item.translation=KIRK_HADIS_TR[item.id]||'';

export function emptyKirkHadisState(){return {startedAt:null,currentId:1,completed:[],sessions:[],highlights:[],notes:[],reviews:[],recalls:[],bookmarks:[],settings:{fontScale:1,focus:false},ui:{screen:'home',selectedId:1,noteFor:null,noteTag:'not',reviewOpenId:null,reviewReveal:false,recallDraft:''}}}
export function normalizeKirkHadisState(raw={}){const b=emptyKirkHadisState();return {...b,...raw,completed:Array.isArray(raw.completed)?raw.completed:[],sessions:Array.isArray(raw.sessions)?raw.sessions:[],highlights:Array.isArray(raw.highlights)?raw.highlights:[],notes:Array.isArray(raw.notes)?raw.notes:[],reviews:Array.isArray(raw.reviews)?raw.reviews:[],recalls:Array.isArray(raw.recalls)?raw.recalls:[],bookmarks:Array.isArray(raw.bookmarks)?raw.bookmarks:[],settings:{...b.settings,...(raw.settings||{})},ui:{...b.ui,...(raw.ui||{})}}}
export const getHadis=id=>KIRK_HADIS_UNITS.find(x=>x.id===Number(id))||null;
export function activeHadis(state){return getHadis(state.currentId)||KIRK_HADIS_UNITS[0]}
export function progressPct(state){return Math.round(clamp((state.completed?.filter(id=>id<=KIRK_HADIS_META.totalUnits).length||0)/KIRK_HADIS_META.totalUnits,0,1)*100)}
export function todayHadisPlan(state,today){
  const s=normalizeKirkHadisState(state); if(!s.startedAt)s.startedAt=today;
  const due=dueReviews(s,today,3); const current=activeHadis(s);
  const recent=s.sessions.filter(x=>daysBetween(x.date,today)>=0&&daysBetween(x.date,today)<=7);
  const heavy=recent.filter(x=>x.feedback==='heavy').length;
  const completedRecent=recent.filter(x=>x.completed).length;
  const confidence=recent.length<3?'Veri topluyor':recent.length<5?'Orta':'Güçlü';
  const mode=heavy>=2?'Sadeleştirilmiş':completedRecent>=4&&heavy===0?'Dengeli + hatırlama':'Dengeli';
  return {date:today,hadis:current,dueReviews:due,minutes:heavy>=2?7:10,mode,confidence,reviewFirst:due.length>=2,why:heavy>=2?'Son günlerde zorlanma arttığı için açıklama bölümünü sade tutuyoruz.':due.length>=2?'Bugün iki veya daha fazla tekrar bekliyor; yeni okumadan önce kısa geri çağırma öneriliyor.':recent.length<3?'İlk günlerde amaç hız değil, sürdürülebilir bir okuma ritmi bulmak.':'Gerçek okuma kayıtlarına göre bir hadislik günlük tempo korunuyor.'};
}
export function recordHadisSession(state,{hadisId,date,minutes=10,feedback='ideal',completed=true}){
  const s=state; const id=Number(hadisId); if(!getHadis(id))throw new Error('Hadis bulunamadı');
  if(!s.startedAt)s.startedAt=date;
  const prev=s.sessions.filter(x=>x.date===date&&x.hadisId===id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];
  const session={id:uid('hs'),hadisId:id,date,minutes:Math.max(1,Number(minutes)||10),feedback,completed:!!completed,createdAt:new Date().toISOString()};
  if(prev){const i=s.sessions.findIndex(x=>x.id===prev.id);s.sessions[i]=session}else s.sessions.push(session);
  if(completed&&!s.completed.includes(id))s.completed.push(id);
  if(completed){scheduleHadisReviews(s,id,date);if(id===s.currentId)s.currentId=Math.min(KIRK_HADIS_META.totalUnits,id+1)};
  return session;
}
export function scheduleHadisReviews(state,hadisId,date){
  const existing=new Set(state.reviews.filter(r=>r.hadisId===Number(hadisId)).map(r=>r.wave));
  const made=[];for(const wave of [3,7])if(!existing.has(wave)){const r={id:uid('hr'),hadisId:Number(hadisId),wave,dueDate:addDays(date,wave),done:false,createdDate:date};state.reviews.push(r);made.push(r)}return made;
}
export function dueReviews(state,today,limit=5){return state.reviews.filter(r=>!r.done&&r.dueDate<=today).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||reviewPriority(a)-reviewPriority(b)).slice(0,limit)}
function reviewPriority(r){return r.kind==='recovery'?0:Number(r.wave)||9}
export function completeHadisReview(state,reviewId,today,result='remembered'){
  const r=state.reviews.find(x=>x.id===reviewId);if(!r)return null;
  r.done=true;r.completedDate=today;r.result=result;
  if((result==='hard'||result==='forgot')&&r.kind!=='recovery'){
    const exists=state.reviews.some(x=>!x.done&&x.hadisId===r.hadisId&&x.kind==='recovery'&&x.createdFrom===r.id);
    if(!exists)state.reviews.push({id:uid('hr'),hadisId:r.hadisId,wave:1,kind:'recovery',label:'Kısa geri çağırma',dueDate:addDays(today,1),done:false,createdDate:today,createdFrom:r.id});
  }
  return r
}
export const RECALL_PROMPTS={
  1:'Niyet hadisinin ana fikrini kendi cümlenle nasıl anlatırsın?',
  2:'İslam, iman ve ihsan arasındaki ilişkiyi hatırladığın kadarıyla yaz.',
  3:'Bu hadiste öne çıkan beş temel esas nelerdi ve neden “temel” diye düşünüyorsun?',
  4:'Kader başlığında bu ünitenin sana öğrettiği yöntem neydi?',
  5:'Dinî bir iddia duyduğunda bu hadis sana hangi kontrol alışkanlığını kazandırıyor?',
  6:'Helal, haram ve şüpheli alanlar konusunda hatırladığın ana ilkeyi yaz.',
  7:'Nasihat kavramını yalnız “öğüt vermek”ten daha geniş düşündüren şey neydi?'
};
export function recallPromptFor(hadisId){return RECALL_PROMPTS[Number(hadisId)]||getHadis(hadisId)?.reflection||'Bu ünitenin ana fikrini kendi cümlenle hatırlamaya çalış.'}
export function recordRecallAttempt(state,{reviewId,today,text='',result='remembered'}){
  const review=state.reviews.find(x=>x.id===reviewId);if(!review)throw new Error('Tekrar bulunamadı');
  const attempt={id:uid('rc'),reviewId,hadisId:review.hadisId,date:today,text:String(text||'').trim(),result,createdAt:new Date().toISOString()};
  state.recalls.push(attempt);completeHadisReview(state,reviewId,today,result);return attempt;
}
export function knowledgeSignal(state,hadisId,today){
  const id=Number(hadisId),completed=state.completed.includes(id),reviews=state.reviews.filter(r=>r.hadisId===id),done=reviews.filter(r=>r.done),open=reviews.filter(r=>!r.done),overdue=open.filter(r=>r.dueDate<today);
  const remembered=done.filter(r=>r.result==='remembered').length,hard=done.filter(r=>r.result==='hard'||r.result==='forgot').length;
  const has3=done.some(r=>Number(r.wave)===3&&r.result==='remembered'),has7=done.some(r=>Number(r.wave)===7&&r.result==='remembered');
  let key='new',label='Yeni',detail='Henüz tamamlanmış okuma kanıtı yok.';
  if(completed){key='building';label='Pekişiyor';detail='Okuma tamamlandı; 3/7 günlük geri çağırma kanıtı bekleniyor.'}
  if(overdue.length){key='recall';label='Geri çağır';detail='Bekleyen tekrar var; yeni içerikten önce kısa hatırlama daha değerli.'}
  else if(hard>0&&remembered===0){key='repair';label='Yeniden bak';detail='Son geri çağırmada zorlanma görüldü; kısa bir toparlama tekrarı açıldı.'}
  else if(has3&&has7){key='stable';label='Oturuyor';detail='3. ve 7. gün geri çağırmaları başarıyla tamamlandı.'}
  else if(remembered>0){key='building';label='Pekişiyor';detail='En az bir geri çağırma başarılı; ikinci kanıt bekleniyor.'}
  const evidence=(completed?1:0)+done.length+(state.notes.some(n=>n.hadisId===id)?1:0);
  return {key,label,detail,evidence,remembered,hard,pending:open.length,overdue:overdue.length}
}
export function knowledgeOverview(state,today){return KIRK_HADIS_UNITS.map(h=>({hadis:h,...knowledgeSignal(state,h.id,today)}))}

export function addHadisHighlight(state,{hadisId,sectionIndex,text,date}){const h={id:uid('hh'),hadisId:Number(hadisId),sectionIndex:Number(sectionIndex),text:String(text||'').trim(),date,createdAt:new Date().toISOString()};if(!h.text)throw new Error('Vurgu metni boş olamaz');const same=state.highlights.find(x=>x.hadisId===h.hadisId&&x.sectionIndex===h.sectionIndex&&x.text===h.text);if(same){state.highlights=state.highlights.filter(x=>x.id!==same.id);return {removed:true,id:same.id}}state.highlights.push(h);return h}
export function addHadisNote(state,{hadisId,sectionIndex=null,text,date,tag='not'}){const t=String(text||'').trim();if(!t)throw new Error('Not boş olamaz');const n={id:uid('hn'),hadisId:Number(hadisId),sectionIndex:sectionIndex===null?null:Number(sectionIndex),text:t,tag,date,createdAt:new Date().toISOString()};state.notes.push(n);return n}
export function toggleHadisBookmark(state,hadisId){const id=Number(hadisId);state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];return state.bookmarks.includes(id)}
export function notebookEntries(state){return KIRK_HADIS_UNITS.map(h=>({hadis:h,notes:state.notes.filter(n=>n.hadisId===h.id),highlights:state.highlights.filter(x=>x.hadisId===h.id),bookmarked:state.bookmarks.includes(h.id)})).filter(x=>x.notes.length||x.highlights.length||x.bookmarked)}
